import type { Hackathon } from './types'

/**
 * Curated coding / product / AI events — remote or Delhi / Mumbai / Gurgaon / Pune / Noida.
 */
export const CURATED_HACKATHONS: Hackathon[] = [
  {
    id: 'curated-sih-2026',
    name: 'Smart India Hackathon 2026',
    url: 'https://www.sih.gov.in/',
    organization: 'Ministry of Education / AICTE',
    location: 'India (software track — finales in major cities incl. Delhi NCR)',
    mode: 'hybrid',
    startDate: '2026-08-01',
    endDate: '2026-11-30',
    dateLabel: 'Aug–Nov 2026',
    prizeAmount: 100000,
    prizeLabel: '₹1,00,000 / problem',
    themes: ['Software', 'AI', 'Product', 'Government'],
    source: 'curated',
    status: 'open',
    featured: true,
    eligibility: 'Indian UG/PG students (teams via college SPOC)',
    notes: 'Prefer software problem statements; skip hardware-only tracks.',
  },
  {
    id: 'curated-hackcbs-2026',
    name: 'HackCBS 7.0',
    url: 'https://hackcbs.tech/',
    organization: 'NSUT / CBS',
    location: 'New Delhi, India',
    mode: 'in-person',
    startDate: '2026-10-17',
    endDate: '2026-10-19',
    dateLabel: 'Oct 2026 (expected)',
    prizeAmount: 500000,
    prizeLabel: '₹5,00,000+',
    themes: ['Open Ended', 'AI', 'Web', 'Product'],
    source: 'curated',
    status: 'upcoming',
    featured: true,
    eligibility: 'College students',
  },
  {
    id: 'curated-hackrx-2026',
    name: 'HackRx 6.0',
    url: 'https://hackrx.in/',
    organization: 'Bajaj Finserv',
    location: 'Pune / Online hybrid, India',
    mode: 'hybrid',
    startDate: '2026-07-15',
    endDate: '2026-08-31',
    dateLabel: 'Jul–Aug 2026',
    prizeAmount: 500000,
    prizeLabel: '₹5,00,000+',
    themes: ['FinTech', 'AI', 'Product', 'Software'],
    source: 'curated',
    status: 'open',
    featured: true,
    eligibility: 'College students in India',
  },
  {
    id: 'curated-solution-challenge-2027',
    name: 'Google Solution Challenge 2027',
    url: 'https://developers.google.com/community/gdsc-solution-challenge',
    organization: 'Google Developer Student Clubs',
    location: 'Online (global)',
    mode: 'online',
    startDate: '2026-12-01',
    endDate: '2027-03-31',
    dateLabel: 'Dec 2026 – Mar 2027 (expected)',
    prizeAmount: 3000,
    prizeLabel: '$3,000+ + mentorship',
    themes: ['AI', 'Mobile', 'Cloud', 'Product', 'UN SDGs'],
    source: 'curated',
    status: 'upcoming',
    featured: true,
    eligibility: 'University students',
  },
  {
    id: 'curated-devfolio-discover',
    name: 'Devfolio Discover',
    url: 'https://devfolio.co/hackathons',
    organization: 'Devfolio',
    location: 'India + Online',
    mode: 'hybrid',
    startDate: '2026-08-01',
    endDate: '2027-06-30',
    dateLabel: 'Ongoing 2026–27',
    prizeAmount: 0,
    prizeLabel: 'Varies',
    themes: ['Software', 'AI', 'Web3', 'Product'],
    source: 'curated',
    status: 'open',
    eligibility: 'Students & builders (India-friendly)',
    notes: 'Hub for Indian student software hackathons.',
  },
  {
    id: 'curated-unstop-hub',
    name: 'Unstop Hackathons',
    url: 'https://unstop.com/hackathons',
    organization: 'Unstop',
    location: 'Online + Delhi / Mumbai / Pune / Noida',
    mode: 'hybrid',
    startDate: '2026-08-01',
    endDate: '2027-06-30',
    dateLabel: 'Ongoing 2026–27',
    prizeAmount: 0,
    prizeLabel: 'Varies',
    themes: ['Coding', 'AI', 'Product'],
    source: 'curated',
    status: 'open',
    eligibility: 'Indian college students',
  },
  {
    id: 'curated-mlh-online',
    name: 'MLH Online Season Events',
    url: 'https://mlh.io/seasons/2026/events',
    organization: 'Major League Hacking',
    location: 'Online',
    mode: 'online',
    startDate: '2026-08-01',
    endDate: '2027-06-30',
    dateLabel: 'Aug 2026 – Jun 2027',
    prizeAmount: 0,
    prizeLabel: 'Varies by event',
    themes: ['Software', 'Beginner Friendly', 'Open Ended'],
    source: 'curated',
    status: 'open',
    eligibility: 'Students — filter for online / digital events',
  },
]
